version: '3.8'

services:
  web:
    build: .
    container_name: budgetwise_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      # This connection string uses the 'db' service name as the host
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on:
      - db
    volumes:
      - .:/app  # This allows you to edit code locally and see changes in container

  db:
    image: mysql:8.0
    container_name: budgetwise_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306" # Exposes MySQL to your local machine if you want to use DBeaver/Workbench
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

