# name: CD - Deploy to AWS ECS

# on:
#   push:
#     branches:
#       - main   # Deploy only when main is updated

# jobs:
#   deploy:
#     name: Build → Push to ECR → Deploy to ECS
#     runs-on: ubuntu-latest

#     steps:
#       # ----------------------------
#       # Checkout Code
#       # ----------------------------
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       # ----------------------------
#       # Configure AWS credentials
#       # ----------------------------
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1        # Change to your region

#       # ----------------------------
#       # Login to AWS ECR
#       # ----------------------------
#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       # ----------------------------
#       # Build & Push Docker image
#       # ----------------------------
#       - name: Build, Tag, Push image to ECR
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: flask-api
#           IMAGE_TAG: latest
#         run: |
#           docker build -t $ECR_REPOSITORY .
#           docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

#       # ----------------------------
#       # Deploy to ECS using new image
#       # ----------------------------
#       - name: Deploy ECS Service
#         uses: aws-actions/amazon-ecs-deploy-task-definition@v2
#         with:
#           task-definition: ecs-task-def.json        # Your task definition file
#           service: flask-service                    # ECS service name
#           cluster: flask-cluster                    # ECS cluster name
#           wait-for-service-stability: true
#           image: ${{ steps.login-ecr.outputs.registry }}/flask-api:latest
